### ISSUE TITLE
Use of missing_after minion attribute

### ISSUE THREAD

**Issue by avkhozov** [kraih/minion#13]
``repair`` executes every ``remove_after`` seconds for each worker https://github.com/kraih/minion/blob/master/lib/Minion/Command/minion/worker.pm#L46. So jobs that processes by abandoned workers are marked as ``failed`` only after ``remove_after`` seconds but not ``missing_after`` seconds. Even for default values (1 day and 10 days) it looks not very good. We can restart the ``failed`` jobs only after 10 days, but not 1 day, as expected by documentation.

Seems that we need two ``repair`` methods ``repair_workers`` and ``repair_jobs`` with it own intervals.

**Comment by kraih** [comment]
I disagree about the need for two methods. Detecting workers without heartbeats quickly is the critical part here, removing old jobs not so much. That's why `missing_after` should determine the `repair` interval.

**Comment by avkhozov** [comment]
Ok, thanks.
