### ISSUE TITLE
Bug in command worker

### ISSUE THREAD

**Issue by Logioniz** [kraih/minion#15]
I have mojo app with minion worker in which i run external process.
I want to have ability to handle stdout when it occur. So, i use Mojo::IOLoop::ReadWriteFork to get this functionality.
When i start external program with Mojo::IOLoop::ReadWriteFork the "close" event not arrive.

Below two example of code. First example have right behaviour (without mojo app), second example (with mojo app) have wrong behaviour.

I don't know which module have bug, this is not obvious, so @jhthorsen maybe you would be interested.

**1-st example**
```perl
#!/usr/bin/perl

use Mojo::IOLoop::ReadWriteFork;
use Minion;

my $minion = Minion->new(Pg => 'postgresql://logioniz@/test');

$minion->add_task(x => sub {
  my ($job, @args) = @_;

  my $fork = Mojo::IOLoop::ReadWriteFork->new;

  $fork->on(close => sub {
    my($fork, $exit_value, $signal) = @_;
    Mojo::IOLoop->stop;
  });

  $fork->start(program => sub { warn $$; `ls` });
  Mojo::IOLoop->start;

  $job->finish;
});

$minion->enqueue('x');

my $worker = $minion->worker;
my $job = $worker->register->dequeue;
my $pid = $job->start;
warn $pid;
while (1) {
  last if $job->is_finished($pid);
  sleep 1;
}

print "Ok!\n";

```

**2-nd example**
```perl
#!/usr/bin/perl

use Mojolicious::Lite;
use Mojo::IOLoop::ReadWriteFork;

app->plugin('Minion' => {Pg => 'postgresql://logioniz@/test'});

app->minion->add_task(x => sub {
  my ($job, @args) = @_;

  my $fork = Mojo::IOLoop::ReadWriteFork->new;

  $fork->on(close => sub {
    my($fork, $exit_value, $signal) = @_;
    Mojo::IOLoop->stop;
  });

  $fork->start(program => sub { warn $$; `ls` });
  Mojo::IOLoop->start;

  $job->finish;
});

app->start;

```

Second example never completed its work.

```bash
$ perl 2.pl minion job -e x
36
$ MOJO_READWRITE_FORK_DEBUG=1 perl 1.pl minion worker
[22304] Child starting (CODE(0x25f12d8) )
[22304] Starting CODE(0x25f12d8) 
[22304] >>> 22338 at 1.pl line 18, <DATA> line 660.\n
```
```bash
$ ps ax | grep  22338
22338 pts/10   Z+     0:00 [perl] <defunct>
```
You see that child process is zombie process.

**Comment by kraih** [comment]
Afraid i don't know much about `Mojo::IOLoop::ReadWriteFork`, so won't be able to do much here. But maybe @jhthorsen can help.

**Comment by kraih** [comment]
@Logioniz I guess you could add more lines from the worker command to your first example, one by one, to locate the actual problem.

**Comment by jhthorsen** [comment]
@Logioniz: what happens if you run the the Mojo::IOLoop::ReadWriteFork code by itself? I mean as a standalone script, without using minion?

This test looks pretty much like the code you have, so I'm not sure why the "close" event is not called: https://github.com/jhthorsen/mojo-ioloop-readwritefork/blob/master/t/close.t

Also, I'm curious of why MOJO_READWRITE_FORK_DEBUG=1 doesn't report the STDERR/OUT from the "program" sub.

**Comment by jhthorsen** [comment]
Also, which version of Mojo::IOLoop::ReadWriteFork and which operation system are you using?

Oh! Maybe you need Mojo::IOLoop->reset inside the task sub, since the IOLoop is already running the main application..? (wild guess)

**Comment by Logioniz** [comment]
@jhthorsen when run script without minion all works well. In first example worker works well too.
I use latest version of both modules (minion and readwritefork).
Command ls not show result because i call it in backtick (it's a new process), so `ls` return string without showing on console.
Mojo::IOLoop->reset doesn't have any positive affect.

Need to take advice of @kraih and continue investigate worker.

```bash
$ perl -MMojo::IOLoop::ReadWriteFork -le 'print $Mojo::IOLoop::ReadWriteFork::VERSION'
0.13
$ perl -MMinion -le 'print $Minion::VERSION'
2.03
$ uname -a
Linux Vena 3.19.0-30-generic #34-Ubuntu SMP Fri Oct 2 22:08:41 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by jhthorsen** [comment]
@Logioniz: Do you have EV installed?

    $ mojo version
    ...
    OPTIONAL
    EV 4.0+                 (4.21)

If so, can you try with ```MOJO_REACTOR=Mojo::Reactor::Poll```

**Comment by Logioniz** [comment]
Yes. Also i add on close warn message "close event". Results are differents:
```bash
$ MOJO_REACTOR=Mojo::Reactor::Poll MOJO_READWRITE_FORK_DEBUG=1 perl 1.pl minion worker
[25397] Child starting (CODE(0x2173518) )
[25397] Starting CODE(0x2173518) 
[25397] >>> 25397 at 1.pl line 20, <DATA> line 660.\n
[25397] Child is dead (0/) 0/0
close event at 1.pl line 16, <DATA> line 660.
```

**Comment by jhthorsen** [comment]
"Different" = It works with ```MOJO_REACTOR=Mojo::Reactor::Poll``` ?

Sorry, I don't understand what "different" means.

**Comment by Logioniz** [comment]
In example 2 close event not called. Program never completed its work. But when set Mojo::Reactor::Poll the close event was called and mojo::ioloop->stop was called and program has finished

**Comment by Logioniz** [comment]
May be need to say that with Mojo::Reactor::Poll  works well?)

**Comment by jhthorsen** [comment]
I honestly have no idea why it's different... What I know is that you hit this code which does some funky stuff using EV: https://github.com/jhthorsen/mojo-ioloop-readwritefork/blob/master/lib/Mojo/IOLoop/ReadWriteFork.pm#L375

I'm sad to say I don't know the inner workings of EV very well. What I do know is that I'm not pulling that code out, since it makes RWF work a lot smoother in cases I use it for.

My suggestion is that we close this issue, since it doesn't seem to be specific to Minion and that you open a new issue in https://github.com/jhthorsen/mojo-ioloop-readwritefork/issues. And if you want to speed up things from my side, it would be awesome if you can make a failing case, without Minion, since I don't know Minion either.

One quick fix would be to add a constant to RWF which disable the ```EV::child``` call, but still allow you to use EV for the rest of your application.

**Comment by kraih** [comment]
Agreed, this does not seem like a Minion specific problem.

**Comment by Logioniz** [comment]
1. I can't write example without Minion which not working.
2. Any example with RWF and Reactor::EV works fine. Even example with extra fork (like minion):
```perl
use Mojo::IOLoop::ReadWriteFork;

my $pid = fork;
die $! unless defined $pid;

if ($pid) {
  warn "Parent: $$";
  waitpid $pid, 0;
} else {
  warn "Child: $$";
  my $fork = Mojo::IOLoop::ReadWriteFork->new;

  $fork->on(close => sub {
    my($fork, $exit_value, $signal) = @_;
    warn 'close';
    Mojo::IOLoop->stop;
  });

  $fork->start(program => 'ls');

  Mojo::IOLoop->start;
}

```

**Comment by Logioniz** [comment]
I think that problem at the junction of Minion and RWF.

**Comment by jhthorsen** [comment]
I just scanned though the Minion code very briefly, and I can't see I spot any reason why it would make any specific issues. (Mostly focused the reading on https://github.com/kraih/minion/blob/master/lib/Minion/Job.pm)

**Comment by jhthorsen** [comment]
Even tried to drop DBD::Pg and waitpid into the mix: https://ssl.thorsen.pm/paste/9dd154dda66c

**Comment by jhthorsen** [comment]
@Logioniz: $SIG{CHLD} = "DEFAULT" was the issue. Fixed in 3be062eae189ee518b4a53192f52568215490432.

**Comment by Logioniz** [comment]
@kraih, @jhthorsen  very thanks.
@kraih now we have another problem. Worker not stop after perform any job when i send signal sigint, sigterm to him.

```sh
$cat 1.pl
#!/usr/bin/perl

use Mojolicious::Lite;
use Mojo::IOLoop;
use Mojo::IOLoop::ReadWriteFork;
use Mojo::Util 'steady_time';

app->plugin('Minion' => {Pg => 'postgresql://logioniz@/test'});

app->minion->add_task(y => sub {
  my ($job, @args) = @_;;
  $job->finish;
});

app->start;
$perl 1.pl minion job
$perl 1.pl minion job -e 'y'
65
$perl 1.pl minion worker
^C^C^C^C
```

When attempt to stop worker via kill -2 or kill -15 nothing happens.

**Comment by Logioniz** [comment]
I have Minion version 2.04

**Comment by kraih** [comment]
Looks like the change needs to be reverted.

**Comment by kraih** [comment]
As far as i can see, the actual problem here is that `EV` takes over `SIGCHLD` when it is loaded, and will greedily fetch the exit/wait status of all children. This kills our process management and means that the `local $SIG{CHLD} = 'DEFAULT'` line is absolutely necessary.

**Comment by jhthorsen** [comment]
Yeah, I think you're right.
```
use strict;
use POSIX 'WNOHANG';

$SIG{CHLD} = sub {
  my $pid = waitpid -1, WNOHANG;
  warn "SIGCHLD: $pid = $?\n" if $pid > 0;
};

if (my $pid = fork) { # parent
  while (1) {
    local $SIG{CHLD} = 'DEFAULT'; # commenting this line out makes the process hang forever
    my $chld = waitpid $pid, WNOHANG;
    warn "while waitpid $chld: $?\n" if $chld;
    last if $chld > 0;
    sleep 1;
  }
}
else { # child
  print "Child $$\n";
  sleep 1;
  exit;
}
```

Would you be interested in a EV patch, or is it too ugly having EV specific code in Minion? Or how about adding ```Mojo::Reactor::child($pid, $ch)``` ..?

**Comment by jhthorsen** [comment]
I can't think of another solution than going back to $SIG{CHLD} = "IGNORE". I've got a commit which makes this work: https://github.com/jhthorsen/mojo-ioloop-readwritefork/commit/8ecab592dfcfcfbc676807ec78bfb85abad2d23f

Can you install that version @Logioniz and try it out?

    $ cpanm https://github.com/jhthorsen/mojo-ioloop-readwritefork/archive/master.tar.gz

**Comment by jhthorsen** [comment]
Also, can you look at the test I wrote @kraih and give me feedback if I'm doing something too crazy?

**Comment by Logioniz** [comment]
@jhthorsen this version works. Test looks fine.

But i can't understand why we have problem with `$SIG{CHLD} = "DEFAULT"` in minion module...

**Comment by jhthorsen** [comment]
@Logioniz: With EV, my code allows EV to "hijack" $SIG{CHLD}. When this is done, ```waitpid()``` is not working properly, since the SIGCHLD handler is reaping the children, which again results in ```waipid()``` to block. This is just the way things work... Nothing special about RWF, Mojolicious or Minion: You need to choose a global strategy for handling dead child processes.

**Comment by jhthorsen** [comment]
```
POSTing upload for Mojo-IOLoop-ReadWriteFork-0.14.tar.gz to https://pause.perl.org/pause/authenquery
PAUSE add message sent ok [200]
```

Enjoy!

**Comment by Logioniz** [comment]
@jhthorsen  very thanks.
