### ISSUE TITLE
Bug with wait timeout in dequeue in Minion::Backend::Pg

### ISSUE THREAD

**Issue by avkhozov** [kraih/minion#17]
Case:
There are two worker that call ``dequeue`` with timeout 10. When one task is added to the queue after 3 seconds, then both worker will receive a notification about the new job, but only one worker receives a job. The second worker must wait for 7 seconds for a new job, but not return ``undef`` immediately after 3 second.

**Comment by kraih** [comment]
The timeout is not guaranteed, it's more like a suggestion, so this is not actually a bug.
