### ISSUE TITLE
Migration-less minions

### ISSUE THREAD

**Issue by shadowcat-mst** [kraih/minion#18]
Currently, the postgresql backend appears to always fire the 'migrate' method on its migrations object; since the minion users in one of my planned deployments will not have permission to run DDL, this is unacceptable.

How do I configure minion to only check the schema version is correct?

**Comment by Grinnz** [comment]
If the migration version is correct then no migration should be performed, it short circuits.
https://metacpan.org/source/SRI/Mojo-Pg-2.15/lib/Mojo/Pg/Migrations.pm#L92 and https://metacpan.org/source/SRI/Mojo-Pg-2.15/lib/Mojo/Pg/Migrations.pm#L51
