### ISSUE TITLE
History

### ISSUE THREAD

**Issue by kraih** [kraih/minion#26]
This is related to #25. Right now we generate statistics on demand, based on the current content of the queue, which only goes back a few days. It might be nice to have persistent statistics as well, like how many jobs the queue has processed during its lifetime, how many failed and got retried, perhaps even daily/weekly summaries.

**Comment by s1037989** [comment]
:+1: Sorry I have nothing more to contribute, but I think you've indicated that you appreciate even user feedback.

**Comment by spicyjack** [comment]
Maybe save job stats in RRD format, if requested by the user?  That way, you can use the existing toolchains for creating graphs and publishing them.

**Comment by kwakwaversal** [comment]
To get statistics, I hook into a couple of job events and write to influxdb. I use Grafana to make shiny graphs.

Might be nice hooking into a single job event to get at the job stats?

$job->on(metrics => sub {
  my ($job, $stats) = @_;
  ...
});

**Comment by kraih** [comment]
Was about to add the number of delayed jobs to our statistics (https://github.com/kraih/minion/commit/f0b50a39dfb5593812a9d65d5789ec74c33c57ab), but then the topic of named queue specific statistics came up again. That's something we need to consider here too.

**Comment by kraih** [comment]
Here's a patch from my personal fork of Minion that adds latency statistics, maybe worth considering. https://gist.github.com/anonymous/a3ad36ffa47e8a6fe46520b8449522d0

**Comment by kraih** [comment]
Judging by the lack of interest, this seems to be a rather unpopular feature. Perhaps Minion does not need it in core, since you can already use events to collect your own statistics.
