### ISSUE TITLE
Batches

### ISSUE THREAD

**Issue by kraih** [kraih/minion#27]
Job dependencies is a topic that keeps coming up every now and then. Personally, i still believe that we don't need a sophisticated dependency system. But it might be nice to have something to synchronize a batch of jobs. Say you have 10 images that need to be resized, and mailed somewhere together afterwards. Wouldn't it be convenient to resize those images in 10 separate jobs, and then have a followup job handle the mailing aspect, once the last image has been resized?

**Comment by s1037989** [comment]
Well, as always for me: :+1:  I love features and options!  I don't know that it's strictly necessary, that is without Batches you're still able to resize the images and send an email.  But with Batches, you might be able to develop a more sophisticated backend module.

On the one hand, you have one routine that resizes *n* images and then emails; on the other hand you have two routines, one that is triggered *n* times and one that is triggered by the *nth* routine (some how).

It's certainly nice from the perspective that you could have one job set up to handle email notifications.  And whether it's resizing images or checking the weather, all jobs could then call the one notification job.

I like it.

**Comment by CodingMinds** [comment]
:+1:
Would be a great feature. At the moment I try to build something similar to your resize example (Render many PDFs and publish/zip them afterwards). A job dependency would be great for this.

**Comment by kraih** [comment]
It's actually really hard to make this efficient and safe.

**Comment by jberger** [comment]
Here is a fairly simple patch which implements job dependencies (calling it "parents", I don't care what the name is). I suspect that (if the optimizer doesn't already do this) the dequeue query could be optimized by checking if j.parents is empty or null first. I also would suspect that this feature would want to be added with an "expires" (or "not_after") to aid cleanup on parent failures and/or updating the repair function to add a similar parent sweep looking for failures.

http://paste.ubuntu.com/16441093/

**Comment by kraih** [comment]
@jberger That looks pretty good, what is the performance cost?

**Comment by jberger** [comment]
@kraih can you paste your benchmark script? I'll check

**Comment by kraih** [comment]
@jberger It's in the repo. 😉 https://github.com/kraih/minion/blob/master/examples/minion_bench.pl

**Comment by jberger** [comment]
For the record a proposal is being developed on this branch: https://github.com/kraih/minion/compare/parents

**Comment by kraih** [comment]
I've committed a first version based on @jberger's work. https://github.com/kraih/minion/commit/6bc239f8b7694e8105198d798427e37768efdcb6

**Comment by kraih** [comment]
This feature has been released with Minion 5.07.
