### ISSUE TITLE
Implement a Wait-for-Job Mechanism

### ISSUE THREAD

**Issue by stephan48** [kraih/minion#28]
Hi,

After a longer talk on IRC sri said that he was open for a new implementation of a mechanism to wait for job completion. 

After some thinking he figured out:
- That the tests would have to be changed fundamentally
- That there would have to be a new backend function for notification & polling
- That a proposed API could be like:

> 21.210933 < sri> my $result = $minion->wait($job_id); and $minion->wait($job_id => sub { my ($minion, $result) = @_; });

(Discussion happened on the 21.02.2016. The times are in GMT+1(CET). Channel was #mojo on irc.perl.org).

Kind Regards,
Stephan

**Comment by kraih** [comment]
It's not actually the tests that need to be changed, but how we currently handle testing with `$minion->perform_jobs`.

**Comment by stephan48** [comment]
Thanks sri! The discussion can also be found in our IRC Log! http://irclog.perlgeek.de/mojo/2016-02-21#i_12078379

**Comment by JamesDooley** [comment]
I agree this would be a very useful feature.  It would allow us to easily queue sub tasks for very complex jobs.  For my use case I can check every few seconds, but it would be a lot better to have Minion respond back, within a reasonable time, when a job is completed.

**Comment by kraih** [comment]
@JamesDooley We already have job dependencies for that.

**Comment by JamesDooley** [comment]
Correct me if I am wrong, but dependencies only allow you to start new jobs inside a parent and exit.    The parent job will not be waiting for the child jobs to complete, which is where the notifications could come in to play.  I would like to wait for a set of child tasks to complete, before moving on to the next step in the parent job.

Although, looking at the test code in that commit, it looks like I could approach this differently and schedule all of the tasks from the parent and finish the job.  Set the dependencies on the tasks that need to happen later, and they will not be run until their parents have completed.

**Comment by kraih** [comment]
I don't think we will do this, now that Mojolicious has native support for subprocesses, there shouldn't be too many use cases left. http://mojolicious.org/perldoc/Mojo/IOLoop#subprocess
