### ISSUE TITLE
Changes don't mention required PostgreSQL version

### ISSUE THREAD

**Issue by shadowcat-mst** [kraih/minion#32]
Since upgrades between PostgreSQL major versions are a Big Deal for a lot of sites, the move from 9.3 to 9.4 and then 9.4 to 9.5 as required versions is, from the point of view of already deployed systems, a massive breaking/backwards incompatible change, and should be documented in both POD and Changes in accordance with your policy for backwards incompatible changes.

(I currently have a customer having to build and deploy a complete extra server because they want new minion features and didn't realise the Changes file was missing such an important change)

**Comment by kraih** [comment]
It was done in 5.0, a major release. The documentation of `Minion::Backend::Pg` specifically mentions it too.
```
Note that this backend uses many bleeding edge features, so only the
latest, stable version of PostgreSQL is fully supported.
```
If you need more backwards compatibility guarantees i recommend 3rd party backends, like `Minion::Backend::Pg91`.

**Comment by shadowcat-mst** [comment]
I can't find any mention of the 9.3 to 9.4 change either.

I'm not objecting to your using the latest stable version of PostgreSQL, I just feel like it should be called out more loudly, just like similarly breaking changes in Mojolicious are - remember I've been a great supporter of your deprecation policy in Mojolicious since it was written up.

Would you take a documentation patch to Minion::Backend::Pg specifically saying that people probably shouldn't put minion in the same postgresql install as other applications so they can upgrade the minion postgresql install safely?

**Comment by kraih** [comment]
Not sure i even agree about deploying Minion on a separate PostgreSQL installation.

**Comment by shadowcat-mst** [comment]
Well, the problem I've hit is that a customer didn't do that, and is now having to *move* it to a spearate PostgreSQL installation, because their primary one can't go to 9.5 without a lot more testing and a scheduled maintenance window.

I mean, basically, the choices here are:

  1. Put minion in a separate database
  2. Don't use Minion::Backend::Pg
  3. Don't upgrade minion

Which of those would you find preferable?

**Comment by kraih** [comment]
That said, PostgreSQL 9.5 was a very special case, it brought new tools specifically for job queues (`SKIP LOCKED`). Doubt we'll have the same problem again anytime soon.

**Comment by shadowcat-mst** [comment]
Ok. Can we please have a warning in Changes in big letters when that happens though (preferably including a retroactive one for the 9.5 change) - a postgres upgrade between major versions is a really, really big deal for a lot of companies and one line in the Minion::Backend::Pg documentation is demonstrably not enough to stop people shooting themselves in the foot.

(once there is such a warning in the changelog they'll probably still do it sometimes anyway, but at that point I'll be happy to tell them they're fools and should read the changelog next time :)

**Comment by kraih** [comment]
Sure, the Minion upgrade should have been harmless though, and easily reversible. We've added a hardcoded version check to `Minion::Backend::Pg` that croaks immediately before making any changes to the schema.

**Comment by shadowcat-mst** [comment]
It was, but they wanted the new features, and it's caused a bit of drama because of the complete lack of warning until they tried to fire things up.

Like I say, the Minion *code* is perfectly fine here, I'm in no way complaining about that. I was just want a warning in BIG RED LETTERS or equivalent in the changelog so people are warned.

**Comment by kraih** [comment]
I've added a note retroactively. https://github.com/kraih/minion/commit/1dfd934fd3bdbba689cdc6744ee5f535ddfbc132
But i'm afraid i do not remember what the PostgreSQL 9.3 situation was, maybe i went straight from MongoDB to PostgreSQL 9.4 and unintentionally supported 9.3 for a time.

**Comment by shadowcat-mst** [comment]
That seems fair enough, and given you're making sure it croak()s if it doesn't see the version of pg it *intends* to support that'll never be a problem again, so I'm untroubled by it.

Thanks very much for the retroactive note!
