### ISSUE TITLE
Asynchronous backends

### ISSUE THREAD

**Issue by kak-tus** [kraih/minion#35]
Hello,
Mojo::Pg is a module with excellent sync/async support.
May be it as a good idea to add async support for minion operations with backends?

**Comment by kraih** [comment]
What would be the benefit?

**Comment by kak-tus** [comment]
Same as asynchronous requests with Mojo:Pg.
For example, not to do synchronous enqueue to remote database.

**Comment by kraih** [comment]
Ok, that's not how it works i'm afraid, an async enqueue would most likely be slower.

**Comment by jberger** [comment]
It is important to remember that for DBD::Pg (which is under Mojo::Pg) the transport is synchronous only waiting on results is asynchronous. So for short queries like insert, you don't even see any benefit since the time spent is all synchronous anyway.

**Comment by kak-tus** [comment]
Synchronous insert to remote database will block all Mojolicious process (or any other process). And in case of network lags process will not do any other enqueue, but will be waiting an syncronous insert and will block any other operations of whole service.

**Comment by jberger** [comment]
@kak-tus read my last post again. Mojo::Pg cannot fix that problem since the underlying db driver does the transport synchronously anyway.

**Comment by avkhozov** [comment]
I think that asynchronous enqueue may be sensitive in Minion, because insert in separate transaction in pg is slow (for example compared to mongodb).

On my machines I can't get more than 70rps enqueues via minion_bench.pl, even with ssd. And this can affect for performance in non-blocking mojolicious application.

**Comment by kak-tus** [comment]
@jberger Thanks, I understood for the second time. I forgot about this.
And if a wanted to get fully non-blocking application, I need to rewrite Mojo::Pg to use as layer AnyEvent::DBI (for example).

**Comment by kraih** [comment]
@avkhozov Even on my laptop i can enqueue 2707 jobs per second. But bulk enqueue might be a sensible addition if there's enough use cases.

**Comment by avkhozov** [comment]
```bash
$ perl minion_bench.pl 
Clean start with 10000 jobs
Enqueued 10000 jobs in 119.491060972214 seconds (83.688/s)
5992 has started 4 workers
6114 will finish 1000 jobs
6115 will finish 1000 jobs
6116 will finish 1000 jobs
6117 will finish 1000 jobs
6115 finished 1000 jobs in 52.6117889881134 seconds (19.007/s)
6114 finished 1000 jobs in 52.6447448730469 seconds (18.995/s)
6117 finished 1000 jobs in 52.6564841270447 seconds (18.991/s)
6116 finished 1000 jobs in 52.6565148830414 seconds (18.991/s)
4 workers finished 1000 jobs each in 52.7988970279694 seconds (75.759/s)
5992 has started 4 workers
6183 will finish 1000 jobs
6184 will finish 1000 jobs
6187 will finish 1000 jobs
6185 will finish 1000 jobs
6187 finished 1000 jobs in 56.3253931999207 seconds (17.754/s)
6185 finished 1000 jobs in 56.3670709133148 seconds (17.741/s)
6183 finished 1000 jobs in 56.3835339546204 seconds (17.736/s)
6184 finished 1000 jobs in 56.3836600780487 seconds (17.736/s)
4 workers finished 1000 jobs each in 56.4647061824799 seconds (70.841/s)
Requesting stats 100 times
Received stats 100 times in 0.419417858123779 seconds (238.426/s)
Repairing 100 times
Repaired 100 times in 0.424486875534058 seconds (235.579/s)
$ 
```

@kraih Are you using some special settings for postgres?

**Comment by kraih** [comment]
No special settings.
```
$ perl examples/minion_bench.pl
Clean start with 10000 jobs
Enqueued 10000 jobs in 3.58394002914429 seconds (2790.225/s)
42451 has started 4 workers
42458 will finish 1000 jobs
42456 will finish 1000 jobs
42455 will finish 1000 jobs
42457 will finish 1000 jobs
42456 finished 1000 jobs in 1.49154090881348 seconds (670.448/s)
42455 finished 1000 jobs in 1.49418020248413 seconds (669.263/s)
42457 finished 1000 jobs in 1.49493598937988 seconds (668.925/s)
42458 finished 1000 jobs in 1.50199198722839 seconds (665.783/s)
4 workers finished 1000 jobs each in 1.52033519744873 seconds (2630.999/s)
42451 has started 4 workers
42464 will finish 1000 jobs
42467 will finish 1000 jobs
42466 will finish 1000 jobs
42465 will finish 1000 jobs
42465 finished 1000 jobs in 1.49702119827271 seconds (667.993/s)
42467 finished 1000 jobs in 1.50133800506592 seconds (666.073/s)
42464 finished 1000 jobs in 1.50320386886597 seconds (665.246/s)
42466 finished 1000 jobs in 1.51235795021057 seconds (661.219/s)
4 workers finished 1000 jobs each in 1.53065395355225 seconds (2613.262/s)
Requesting stats 100 times
Received stats 100 times in 0.514863014221191 seconds (194.226/s)
Repairing 100 times
Repaired 100 times in 0.339805126190186 seconds (294.286/s)
```

**Comment by jberger** [comment]
> And if a wanted to get fully non-blocking application, I need to rewrite Mojo::Pg to use as layer AnyEvent::DBI (for example).

Again. The problem is DBI. So no.

**Comment by kak-tus** [comment]
@jberger In case of AnyEvent::DBI transport queries is going in forked process, so main process is blocked only at local socket writing.

**Comment by jberger** [comment]
You can do that with Mojo::IOLoop::ForkCall or Mojo::IOLoop::ReadWriteFork too. That said, further discussion along these lines should not continue here.
