### ISSUE TITLE
more gentle waitpid check

### ISSUE THREAD

**Issue by avkhozov** [kraih/minion#36]
Now ``Minion::Job::is_finished`` wait for actual ``$pid`` from ``waitpid`` https://github.com/kraih/minion/blob/v5.08/lib/Minion/Job.pm#L28 and if someone already waiting this pid, than ``waitpid`` will return ``-1`` instead of ``$pid`` and ``is_finished`` will never return 1.

* Minion version: 5.08
* Perl version: any
* Operating system: linux

### Steps to reproduce the behavior

```perl
#!/usr/bin/perl

use Mojolicious::Lite;
use Time::HiRes 'sleep';
use Test::Mojo;
use Test::More;

my $sleep = 0.1;

plugin Minion => {Pg => 'postgresql://and@/og'};
app->minion->add_task(test => sub { sleep $sleep and shift->finish('ok'); });

get '/' => sub {
  my $c = shift->render_later;
  $c->minion->enqueue('test');
  Mojo::IOLoop->timer(0.3 => sub { $c->rendered(201); });
};

my $t = Test::Mojo->new;
app->minion->reset;

my ($job, $pid);
my $worker = app->minion->worker->register;

app->minion->on(
  enqueue => sub {
    if (my $j = $worker->dequeue) {
      $job = $j;
      $pid = $job->start;
    }
  }
);

$t->get_ok('/')->status_is(201);
say 'waiting...' and sleep 0.1 until $job->is_finished($pid);

$worker->unregister;
done_testing;
```

### Expected behavior

```bash
$ prove -v 1.pl
1.pl .. 
ok 1 - GET /
ok 2 - 201 Created
waiting...
waiting...
waiting...
waiting...
waiting...
waiting...
1..2
ok
All tests successful.
Files=1, Tests=2,  1 wallclock secs ( 0.03 usr  0.00 sys +  0.28 cusr  0.03 csys =  0.34 CPU)
Result: PASS
$ 
```

### Actual behavior

If ``$sleep`` less than timeout in ``Mojo::IOLoop->timer`` test never finished.

```bash
$ prove -v 1.pl
1.pl .. 
ok 1 - GET /
ok 2 - 201 Created
waiting...
waiting...
waiting...
waiting...
waiting...
waiting...
waiting...
waiting...
waiting...
waiting...
waiting...
waiting...
waiting...
waiting...
waiting...
waiting...
^C
$ 
```

**Comment by kraih** [comment]
Afraid i don't understand the description, there's some broken english that doesn't make much sense to me.

**Comment by genio** [comment]
Attempt at fixing the English:

Currently, ```Minion::Job::is_finished``` waits for the actual ```$pid``` from ```waitpid``` as seen here: https://github.com/kraih/minion/blob/v5.08/lib/Minion/Job.pm#L28
If someone is already waiting for this pid, then ```waitpid``` will return ```-1``` instead of ```$pid``` and ```is_finished``` will never return ```1```.

**Comment by kraih** [comment]
Why would there be two contesting `waitpid` calls?

**Comment by kraih** [comment]
Anyway, it appears nobody on IRC understood this issue, so i have to close it for now.

**Comment by avkhozov** [comment]
Sorry for my bad english.

You can run example with strace ``strace -f prove -v t.pl`` (https://gist.github.com/anonymous/1e774e04f88f46d102985bae7aec2431)

and see, that a ``waitpid`` call twice:

first (which returning actual pid):
``[pid 21736] wait4(-1, [{WIFEXITED(s) && WEXITSTATUS(s) == 0}], WNOHANG|WSTOPPED|WCONTINUED, NULL) = 21740`` on line 7002

and next calls from ``is_finished``:

```[pid 21736] wait4(21740, 0x7ffe54375dd4, WNOHANG, NULL) = -1 ECHILD (No child processes)
[pid 21736] write(1, "waiting...\n", 11) = 11
[pid 21736] nanosleep({0, 100000000},  <unfinished ...>```

``waitpid`` in  ``is_finished`` method always get -1 instead of actual pid (21740).

What is wrong in my test, which causes additional waitpid?

**Comment by jberger** [comment]
EV is eating your zombie. Try adding `BEGIN { $ENV{MOJO_REACTOR} = 'Mojo::Reactor::Poll' }` at the top of your file.

I could tell by the strace output since the process is reaped before the response is written to the wire. Therefore something before the `is_finished` has to be reaping. For future reference it isn't a bad idea to use the Poll reactor in tests.

**Comment by jberger** [comment]
A safer tests might be to check `$job->info->{state}` for finished or failed since that will check against the database. Of course you still should probably call `is_finished` to cleanup the zombie just in case.

**Comment by jberger** [comment]
This is what ate the zombie: https://metacpan.org/pod/EV#CHILD-WATCHERS---watch-out-for-process-status-changes

**Comment by avkhozov** [comment]
@jberger thanks, with ``Mojo::Reactor::Poll`` all fine.

And yes, I have already rewrite my tests to check ``$job->info->{state}``.

**Comment by avkhozov** [comment]
@jberger ``$SIG{CHLD} = 'DEFAULT';`` also help to work with EV.

So any process with loaded EV need test ``waitpid`` result for -1 or disable SIGCHILD handler.
