### ISSUE TITLE
Kill running jobs

### ISSUE THREAD

**Issue by avkhozov** [kraih/minion#37]
If you, by chance, enqueue odd job (which loops or just incorrectly works for a long time) to a big minion cluster, that you need make great effort to stop it — find a worker host, find a process in which job is performed and kill it.

It would be nice, if ``minion job`` would have ``kill`` option for stop and fail those job automatically.

**Comment by kraih** [comment]
This sounds like a worker remote control feature for an Admin UI. We could allow active jobs to be killed, worker pools to grow/shrink, and maybe even change the queues a worker is watching. Doubt we'll see this before #25 has been implemented though.

**Comment by avkhozov** [comment]
May be worker remote control feature can be done not only for Admin UI, but also for ``minion admin`` sub-commands? Sometimes shell commands more convenient for automation than a web interface.

**Comment by kraih** [comment]
I've thought a little bit about this, and on the database layer this might be easiest to implement by adding an `inbox` column (`array` of `jsonb` perhaps) to the `minion_workers` table. New broadcast messages could be added to the `inbox` with a new backend method like `send_worker($worker_id, {some => 'data'})`, and we would remove all messages from the `inbox` with the already existing `register_worker` method at the same time heartbeats are handled.

How those messages are then processed inside the worker process shouldn't be too hard to figure out. And sending them from the `job` command would be trivial as well.

**Comment by kraih** [comment]
The broadcast mechanism could also be used for #34.

**Comment by kraih** [comment]
A worker remote control command system has just been added. https://github.com/kraih/minion/commit/4054eac5823fd8bdf6b6c0bf4735af3d1d28ee85

**Comment by kraih** [comment]
It would be pretty easy now to add a command to kill a specific job remotely, we just have to figure out portability issues. Perhaps we should just stop supporting versions of Perl with fork emulation, like we did in Mojolicious for subprocesses.

**Comment by kraih** [comment]
And you can now kill jobs remotely too. https://github.com/kraih/minion/commit/1360f5a9f65d4ec24e66f1fefe283a98e6cf056e

**Comment by avkhozov** [comment]
Thanks!
