### ISSUE TITLE
Mistake in documentation

### ISSUE THREAD

**Issue by akarelas** [kraih/minion#38]
* Minion version: 5.08
* Perl version: -
* Operating system: -

Documentation of https://metacpan.org/pod/Minion#remove_after says: "jobs that have reached the state finished and have no unresolved dependencies". But jobs that have reached the state finished cannot have unresolved dependencies.

Did you mean dependent jobs instead of dependencies?

**Comment by kraih** [comment]
Has this been discussed on IRC yet? Don't think GitHub issues are a good place for nitpicking about documentation, i fear this issue would just stay open forever.

**Comment by akarelas** [comment]
I'll raise on IRC now.
