### ISSUE TITLE
Document MySQL user privileges

### ISSUE THREAD

**Issue by satmovi** [kraih/minion#41]
* Minion version: latest
* Perl version: 5.16
* Operating system: centos

Hello, 
I've tried to install our worker on the new machine and I face some mysql errors:

DBD::mysql::st execute failed: TRIGGER command denied to user 'worker'@'172.31.48.229' for table 'mojo_pubsub_notify' at /usr/local/share/perl5/Mojo/mysql/Database.pm line 47

If it's possible please mention what are the required privileges for minion to run.

Thanks,
Ovidiu

**Comment by kraih** [comment]
I'm sorry, but MySQL is not supported by Minion.

**Comment by satmovi** [comment]
It was never supported? Because I'm using it successfully :) It work now as I just added the TRIGGER privilege. 
Anyway, it would be very nice to be supported because mysql is our main db. We use it with mysql since about 3-4 months ago and this is the first time we encounter a problem with it.

**Comment by kraih** [comment]
There's a 3rd party module `Minion::Backend::mysql` on CPAN, you might want to contact its author instead.
