### ISSUE TITLE
Detailed worker stats

### ISSUE THREAD

**Issue by avkhozov** [kraih/minion#42]
Now the command ``minion job -w`` return list of workers (id and host:port). It would be nice, if this command will also return information about watching queues and numbers of jobs.

I think it can be done via ``register_worker`` method, each worker would update info about self every heartbeat interval.

**Comment by kraih** [comment]
I think this is part of #26.

**Comment by avkhozov** [comment]
Hmm, I meant the current state of workers, not history. Like a current number of jobs (``$self->{max}`` from ``Minion::Command::minion::worker``), which was setup from ``-j`` args or jobs command.

**Comment by kraih** [comment]
Suppose this could be considered something else than stats, if all you're collecting is the maximum number of concurrent jobs and the named queues the worker is watching. But then it also seems hardly worth the cost.
