### ISSUE TITLE
Minion workers could not start on Windows 7 x64

### ISSUE THREAD

**Issue by wlai2768** [kraih/minion#45]
* Minion version: 6.0
* Perl version: v5.24.0
* Operating system: Microsoft Windows [Version 6.1.7601]

### Steps to reproduce the behavior
CMD> perl script\myapp.pl minion worker

### Expected behavior
Expect worker to start normally as v5.09

### Actual behavior
CMD> perl script\myapp.pl minion worker
Minion workers do not support fork emulation

**Comment by kraih** [comment]
Afraid this is intentional, Windows Perl is no longer supported. Instead we recommend the use of the Windows Subsystem for Linux. http://mojolicious.org/perldoc/Mojolicious/Guides/FAQ#How-well-is-Windows-supported-by-Mojolicious
