### ISSUE TITLE
Multiple tasks enqueue

### ISSUE THREAD

**Issue by kak-tus** [kraih/minion#50]
Is it in plans to add support to enqueue multiple tasks at once (with one postgresql query, as example)?

**Comment by kraih** [comment]
No plans.

**Comment by kak-tus** [comment]
If I will program this functionality, there are any reasons not to accept it in upstream?

**Comment by kraih** [comment]
Well, are there good reasons to have it?

**Comment by kak-tus** [comment]
I need to insert many (1000, 10000,...) tasks in a single action. It's not very fast.
Action is blocked and waiting for this many inserts.
Of course, I can create one task (that inserts other tasks), but multiple-at-once may be better for DB performance.

**Comment by kraih** [comment]
I've brought this up a few times on IRC, and it doesn't look like there is much interest in this feature i'm afraid.

**Comment by kraih** [comment]
Unless there's a very simple and clean patch that doesn't cost us much, i don't see this happening.

**Comment by kraih** [comment]
This might be related to #52, which needs a test case with about a million jobs.

**Comment by kraih** [comment]
Ok, benchmarks that require a lot of jobs to be enqueued very fast are a very good use case for this. But sadly there have been no proposals yet, and not a single comment in three weeks. So i'll close this issue for now.
