### ISSUE TITLE
Inquiry: Recurring jobs feature.

### ISSUE THREAD

**Issue by hchienjo** [kraih/minion#56]
* Minion version: 7.05
* Perl version: 5.22.1
* Operating system: Ubuntu gnome 16.04.3 LTS

### Steps to reproduce the behavior
This is not a bug _per se_, but is it possible to have recurring jobs that can be scheduled to run at:

1. Specific days.
2. Specific time of day.

The only way to achieve some form of recurring jobs is to have a job to reschedule itself before finishing. Something like this:

```
$app->minion->add_task(
    sloth_add => sub {
        my ( $job, $a, $b ) = @_;
        sleep 20;
        my $sum = $a + $b;

        #schedule job again to run 10 seconds from now
        $app->minion->enqueue(
            sloth_add => [ $a, $b ] => { priority => 5, delay => 10 } );
        $job->finish( { result => $sum } );
    }
);
````

### Expected behavior
What if instead of a job scheduling itself, there could be specific parameters (in the hash) that are passed when queuing a job which the worker will use to schedule recurring jobs using cron-style format.
```
#schedule job to run at midnight. n_runs being number of times to run so
#this will run at midnight for ten days
$app->minion->enqueue(
    sloth_add => [ $a, $b ] => { n_runs => 10, schedule => "@midnight" } );

#run once every 24 hours, indefinitely
$app->minion->enqueue( sloth_add => [ $a, $b ] => { schedule => "@daily" } );
```

### Actual behavior
Currently not implemented.

**Comment by kraih** [comment]
This has been discussed before. https://github.com/kraih/minion/issues/24

**Comment by hchienjo** [comment]
Thanks. Let me read the discussion.

**Comment by kraih** [comment]
The bottom line is that we rely on cron and expiring locks for this.
