### ISSUE TITLE
"Not a HASH reference" in Minion::Admin UI

### ISSUE THREAD

**Issue by wneessen** [kraih/minion#67]
* Minion version: 8.12
* Perl version: 5.24.3
* Operating system: MacOS X 10.13.3

### Steps to reproduce the behavior
While testing out the new (very fancy) Minion Admin UI, I was seeing nice graphs of the jobs that were processed. When I clicked on "Finished" (=> /minion/jobs?state=finished) it returns a error page stating "Not a HASH reference".

### Expected behavior
I've never seen the "Finished jobs" page so far, but I would expect to see it, when clicking that link ;)

### Actual behavior
[Tue Mar 20 23:12:58 2018] [debug] Routing to a callback
[Tue Mar 20 23:12:58 2018] [error] Not a HASH reference at /Users/wneessen/perl5/perlbrew/perls/perl-5.24.1/lib/site_perl/5.24.3/Mojolicious/Plugin/Minion/Admin.pm line 53.

This actually happens with any of the jobs links in the navigation.

**Comment by Grinnz** [comment]
What version of Minion?

**Comment by wneessen** [comment]
Check the first line of my report ;)
It's 8.12

**Comment by Grinnz** [comment]
Strange, because line 53 of that version has no hashes: https://metacpan.org/source/SRI/Minion-8.12/lib/Mojolicious/Plugin/Minion/Admin.pm#L53

**Comment by Grinnz** [comment]
What backend are you using?

**Comment by wneessen** [comment]
I can confirm, that this is also the line, which is highlighted in the development error page. I am using SQLite3 as backend for Minion.

Here is the full stacktrace from the dev-error page (in case that helps):
/Users/wneessen/perl5/perlbrew/perls/perl-5.24.1/lib/site_perl/5.24.3/Mojolicious/Plugin/Minion/Admin.pm:53
--
/Users/wneessen/perl5/perlbrew/perls/perl-5.24.1/lib/site_perl/5.24.3/Mojolicious.pm:145
/Users/wneessen/perl5/perlbrew/perls/perl-5.24.1/lib/site_perl/5.24.3/Mojolicious/Plugins.pm:15
/Users/wneessen/perl5/perlbrew/perls/perl-5.24.1/lib/site_perl/5.24.3/Mojolicious/Plugins.pm:18
/Users/wneessen/perl5/perlbrew/perls/perl-5.24.1/lib/site_perl/5.24.3/Mojolicious/Routes.pm:87
/Users/wneessen/perl5/perlbrew/perls/perl-5.24.1/lib/site_perl/5.24.3/Mojolicious/Routes.pm:94
/Users/wneessen/perl5/perlbrew/perls/perl-5.24.1/lib/site_perl/5.24.3/Mojolicious/Routes.pm:35
/Users/wneessen/perl5/perlbrew/perls/perl-5.24.1/lib/site_perl/5.24.3/Mojolicious/Routes.pm:44
/Users/wneessen/perl5/perlbrew/perls/perl-5.24.1/lib/site_perl/5.24.3/Mojolicious.pm:136
/Users/wneessen/perl5/perlbrew/perls/perl-5.24.1/lib/site_perl/5.24.3/Mojolicious.pm:146
/Users/wneessen/perl5/perlbrew/perls/perl-5.24.1/lib/site_perl/5.24.3/Mojolicious/Plugins.pm:15
/Users/wneessen/perl5/perlbrew/perls/perl-5.24.1/lib/site_perl/5.24.3/Mojolicious.pm:208
/Users/wneessen/perl5/perlbrew/perls/perl-5.24.1/lib/site_perl/5.24.3/Mojolicious.pm:208
/Users/wneessen/perl5/perlbrew/perls/perl-5.24.1/lib/site_perl/5.24.3/Mojolicious/Plugins.pm:15
/Users/wneessen/perl5/perlbrew/perls/perl-5.24.1/lib/site_perl/5.24.3/Mojolicious/Plugins.pm:18
/Users/wneessen/perl5/perlbrew/perls/perl-5.24.1/lib/site_perl/5.24.3/Mojolicious.pm:152
/Users/wneessen/perl5/perlbrew/perls/perl-5.24.1/lib/site_perl/5.24.3/Mojo/Server.pm:68
/Users/wneessen/perl5/perlbrew/perls/perl-5.24.1/lib/site_perl/5.24.3/Mojo/EventEmitter.pm:15
/Users/wneessen/perl5/perlbrew/perls/perl-5.24.1/lib/site_perl/5.24.3/Mojo/Server/Daemon.pm:103
/Users/wneessen/perl5/perlbrew/perls/perl-5.24.1/lib/site_perl/5.24.3/Mojo/EventEmitter.pm:15
/Users/wneessen/perl5/perlbrew/perls/perl-5.24.1/lib/site_perl/5.24.3/Mojo/Transaction/HTTP.pm:60
/Users/wneessen/perl5/perlbrew/perls/perl-5.24.1/lib/site_perl/5.24.3/Mojo/Server/Daemon.pm:218
/Users/wneessen/perl5/perlbrew/perls/perl-5.24.1/lib/site_perl/5.24.3/Mojo/Server/Daemon.pm:199
/Users/wneessen/perl5/perlbrew/perls/perl-5.24.1/lib/site_perl/5.24.3/Mojo/EventEmitter.pm:15
/Users/wneessen/perl5/perlbrew/perls/perl-5.24.1/lib/site_perl/5.24.3/Mojo/IOLoop/Stream.pm:99
/Users/wneessen/perl5/perlbrew/perls/perl-5.24.1/lib/site_perl/5.24.3/Mojo/IOLoop/Stream.pm:48
/Users/wneessen/perl5/perlbrew/perls/perl-5.24.1/lib/site_perl/5.24.3/Mojo/Reactor/Poll.pm:143
/Users/wneessen/perl5/perlbrew/perls/perl-5.24.1/lib/site_perl/5.24.3/Mojo/Reactor/Poll.pm:143
/Users/wneessen/perl5/perlbrew/perls/perl-5.24.1/lib/site_perl/5.24.3/Mojo/Reactor/EV.pm:46
/Users/wneessen/perl5/perlbrew/perls/perl-5.24.1/lib/site_perl/5.24.3/Mojo/Reactor/EV.pm:25
/Users/wneessen/perl5/perlbrew/perls/perl-5.24.1/lib/site_perl/5.24.3/Mojo/Reactor/EV.pm:25
/Users/wneessen/perl5/perlbrew/perls/perl-5.24.1/lib/site_perl/5.24.3/Mojo/IOLoop.pm:136
/Users/wneessen/perl5/perlbrew/perls/perl-5.24.1/lib/site_perl/5.24.3/Mojo/Server/Daemon.pm:39
/Users/wneessen/perl5/perlbrew/perls/perl-5.24.1/lib/site_perl/5.24.3/Mojo/Server/Morbo.pm:69
/Users/wneessen/perl5/perlbrew/perls/perl-5.24.1/lib/site_perl/5.24.3/Mojo/Server/Morbo.pm:54
/Users/wneessen/perl5/perlbrew/perls/perl-5.24.1/lib/site_perl/5.24.3/Mojo/Server/Morbo.pm:34
/Users/wneessen/perl5/perlbrew/perls/perl-5.24.1/bin/morbo:19

**Comment by Grinnz** [comment]
Make sure you are using Minion::Backend::SQLite 3.000+. There was an incompatible change in Minion that requires this version.

**Comment by wneessen** [comment]
Wonderful. That did the job. Updated to 3.003 and it is working as expected. Thanks for the quick turnaround!
