### ISSUE TITLE
Prevent duplicate jobs

### ISSUE THREAD

**Issue by ravengerUA** [kraih/minion#7]
For example, I have some items in my shop in "books" category. When I'm updating a book, I should update a search index for this category, and I could create a task and enqueue some job

````perl
$minion->add_task(
  update_index => sub {
    my ($job, $type) = @_;
    # a lot of code
    # about 1 minute to execute
  }
);

$minion->enqueue(update_index => ['books']);
````

But I could edit this item again and I will get two similar (inactive) tasks. But I don't want to do the same job twice.

````perl

$VAR1 = [
          {
            'task' => 'update_index',
            'created' => '1417737737.14251',
            'retries' => '0',
            'priority' => '0',
            'delayed' => '1',
            'state' => 'inactive',
            'id' => 'ff8a853f39bab0e5cb962e801ac3b857',
            'args' => [
                        'books'
                      ]
          },
          {
            'state' => 'inactive',
            'delayed' => '1',
            'args' => [
                        'books'
                      ],
            'id' => 'e8320bd49ccba196c9330721981497c7',
            'task' => 'update_index',
            'priority' => '0',
            'retries' => '0',
            'created' => '1417737737.14208'
          }
        ];
````

I need some feature which helps me to prevent duplicate jobs. Dou you have any idea how to implement that? I could do it in my own backend, but it will be good if it is a standart solution for all backends.

**Comment by kraih** [comment]
It has been 3 months now, and we have not reached consensus on this, so i'll close this issue.

**Comment by avkhozov** [comment]
It seems that the ```lock``` option for inactive tasks would be good. Are there any reasons not implement this?

It would be very useful for enqueue tasks via crontab from multiple servers for fault tolerance, using for ```lock``` the task name and time accurate to the minute.

**Comment by kraih** [comment]
@avkhozov Lack of interest is the main reason.
